name: Automate Release Notes
description: 'Generates release notes based on commit messages since the last tag'
inputs:
  default-branch: 
    description: 'default branch or tag to compare'
    required: false
    default: 'origin/main'
runs:
  using: "composite"
  steps:
    - name: Get Previous tag
      run: echo "PREV=$(git describe --abbrev=0 --tags $LAST_TAG^)" >> $GITHUB_ENV
      shell: bash
      env:
        LAST_TAG: ${{ github.ref_name }}
    
    - name: List files
      run: ls -al
      shell: bash

    - name: Generate Release Notes
      run: ./generate-notes.sh
      shell: bash
      env:
        LAST_TAG: ${{ github.ref_name }}

    - name: Output release notes
      run: cat release-notes.md
      shell: bash
